kind: Service
apiVersion: v1
metadata:
  name: $NAME-service
  labels:
    app: $NAME-service
  namespace: ikomida
  annotations:
    cloud.google.com/backend-config: '{"ports": {"1988":"$NAME-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: $NAME
  ports:
    - protocol: TCP
      port: 1988
      targetPort: 1988
